package pl.gov.ms.msepo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:37.172+01:00
 * Generated source version: 3.0.6
 * 
 */
@WebServiceClient(name = "EpoService", 
                  wsdlLocation = "file:/D:/dane/projekty/camel/cmlhelo/src/main/resources/wsdl/EPO.wsdl",
                  targetNamespace = "http://ms.gov.pl/msepo") 
public class EpoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ms.gov.pl/msepo", "EpoService");
    public final static QName EpoWebService = new QName("http://ms.gov.pl/msepo", "EpoWebService");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/dane/projekty/camel/cmlhelo/src/main/resources/wsdl/EPO.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EpoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/dane/projekty/camel/cmlhelo/src/main/resources/wsdl/EPO.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EpoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EpoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EpoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EpoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EpoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IEpoContract
     */
    @WebEndpoint(name = "EpoWebService")
    public IEpoContract getEpoWebService() {
        return super.getPort(EpoWebService, IEpoContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEpoContract
     */
    @WebEndpoint(name = "EpoWebService")
    public IEpoContract getEpoWebService(WebServiceFeature... features) {
        return super.getPort(EpoWebService, IEpoContract.class, features);
    }

}
