
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package pl.gov.ms.msepo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:37.094+01:00
 * Generated source version: 3.0.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "EpoService",
                      portName = "EpoWebService",
                      targetNamespace = "http://ms.gov.pl/msepo",
                      wsdlLocation = "file:/D:/dane/projekty/camel/cmlhelo/src/main/resources/wsdl/EPO.wsdl",
                      endpointInterface = "pl.gov.ms.msepo.IEpoContract")
                      
public class EpoWebServiceImpl implements IEpoContract {

    private static final Logger LOG = Logger.getLogger(EpoWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekPoGuidach(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  guidPrzesylki )*
     */
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData pobierzStatusyPrzesylekPoGuidach(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki) throws IEpoContractPobierzStatusyPrzesylekPoGuidachPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekPoGuidachOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekPoGuidach");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(guidPrzesylki);
        try {
            org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPoGuidachPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoGuidach_PrzesylkiOutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekPoGuidachOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoGuidach_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#importZbioruEkn(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  xml )*
     */
    public org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData importZbioruEkn(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String xml) throws IEpoContractImportZbioruEknOutputDataFaultFaultMessage , IEpoContractImportZbioruEknImportZbiorEknOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation importZbioruEkn");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(xml);
        try {
            org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractImportZbioruEknOutputDataFaultFaultMessage("IEpoContract_ImportZbioruEkn_OutputDataFault_FaultMessage...");
        //throw new IEpoContractImportZbioruEknImportZbiorEknOutputDataFaultFaultMessage("IEpoContract_ImportZbioruEkn_ImportZbiorEknOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekPoNumerachNadawczych(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring  numeryNadawcze )*
     */
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData pobierzStatusyPrzesylekPoNumerachNadawczych(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze) throws IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekPoNumerachNadawczych");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numeryNadawcze);
        try {
            org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoNumerachNadawczych_PrzesylkiOutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoNumerachNadawczych_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekZaOkres(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)javax.xml.datatype.XMLGregorianCalendar  dataOd ,)javax.xml.datatype.XMLGregorianCalendar  dataDo ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  guidPrzesylki ,)java.lang.Integer  distinct )*
     */
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData pobierzStatusyPrzesylekZaOkres(java.lang.String userName,java.lang.String password,java.lang.String apiKey,javax.xml.datatype.XMLGregorianCalendar dataOd,javax.xml.datatype.XMLGregorianCalendar dataDo,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki,java.lang.Integer distinct) throws IEpoContractPobierzStatusyPrzesylekZaOkresPrzesylkiOutputShortDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekZaOkresOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekZaOkres");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(dataOd);
        System.out.println(dataDo);
        System.out.println(guidPrzesylki);
        System.out.println(distinct);
        try {
            org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekZaOkresPrzesylkiOutputShortDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekZaOkres_PrzesylkiOutputShortDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekZaOkresOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekZaOkres_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#importZbioruEknZip(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  zipFile )*
     */
    public org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData importZbioruEknZip(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String zipFile) throws IEpoContractImportZbioruEknZipOutputDataFaultFaultMessage , IEpoContractImportZbioruEknZipImportZbiorEknOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation importZbioruEknZip");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(zipFile);
        try {
            org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractImportZbioruEknZipOutputDataFaultFaultMessage("IEpoContract_ImportZbioruEknZip_OutputDataFault_FaultMessage...");
        //throw new IEpoContractImportZbioruEknZipImportZbiorEknOutputDataFaultFaultMessage("IEpoContract_ImportZbioruEknZip_ImportZbiorEknOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring  numeryNadawcze )*
     */
    public org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData pobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze) throws IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage , IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numeryNadawcze);
        try {
            org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage("IEpoContract_PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage("IEpoContract_PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych_ListaDoreczenPdfOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzHistoriePrzesylkiPoGuidPrzesylki(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  idPrzesylka )*
     */
    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData pobierzHistoriePrzesylkiPoGuidPrzesylki(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String idPrzesylka) throws IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiHistoriaPrzesylkiOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzHistoriePrzesylkiPoGuidPrzesylki");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(idPrzesylka);
        try {
            org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoGuidPrzesylki_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiHistoriaPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoGuidPrzesylki_HistoriaPrzesylkiOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekPoGuidachXml(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  guidPrzesylki )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzStatusyPrzesylekPoGuidachXml(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki) throws IEpoContractPobierzStatusyPrzesylekPoGuidachXmlPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekPoGuidachXmlOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekPoGuidachXml");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(guidPrzesylki);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPoGuidachXmlPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoGuidachXml_PrzesylkiOutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekPoGuidachXmlOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoGuidachXml_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#nadanieZbioruEknZip(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  zipFile )*
     */
    public org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData nadanieZbioruEknZip(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String zipFile) throws IEpoContractNadanieZbioruEknZipOutputDataFaultFaultMessage , IEpoContractNadanieZbioruEknZipNadajZbiorEknOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation nadanieZbioruEknZip");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(zipFile);
        try {
            org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractNadanieZbioruEknZipOutputDataFaultFaultMessage("IEpoContract_NadanieZbioruEknZip_OutputDataFault_FaultMessage...");
        //throw new IEpoContractNadanieZbioruEknZipNadajZbiorEknOutputDataFaultFaultMessage("IEpoContract_NadanieZbioruEknZip_NadajZbiorEknOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzListeStatusowPrzesylek(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey )*
     */
    public org.datacontract.schemas._2004._07.epowslib.StatusPrzesylkiOutputData pobierzListeStatusowPrzesylek(java.lang.String userName,java.lang.String password,java.lang.String apiKey) throws IEpoContractPobierzListeStatusowPrzesylekOutputDataFaultFaultMessage , IEpoContractPobierzListeStatusowPrzesylekStatusPrzesylkiOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzListeStatusowPrzesylek");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        try {
            org.datacontract.schemas._2004._07.epowslib.StatusPrzesylkiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzListeStatusowPrzesylekOutputDataFaultFaultMessage("IEpoContract_PobierzListeStatusowPrzesylek_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzListeStatusowPrzesylekStatusPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzListeStatusowPrzesylek_StatusPrzesylkiOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekPoNumerachNadawczychXml(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring  numeryNadawcze )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzStatusyPrzesylekPoNumerachNadawczychXml(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze) throws IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekPoNumerachNadawczychXml");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numeryNadawcze);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoNumerachNadawczychXml_PrzesylkiOutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoNumerachNadawczychXml_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylek(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.Integer  pageIndex ,)java.lang.Integer  pageSize ,)java.lang.String  sortColumn ,)java.lang.String  sortDirection ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringstring  filtersValues )*
     */
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData pobierzStatusyPrzesylek(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.Integer pageIndex,java.lang.Integer pageSize,java.lang.String sortColumn,java.lang.String sortDirection,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringstring filtersValues) throws IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylek");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(pageIndex);
        System.out.println(pageSize);
        System.out.println(sortColumn);
        System.out.println(sortDirection);
        System.out.println(filtersValues);
        try {
            org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylek_PrzesylkiOutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylek_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)javax.xml.datatype.XMLGregorianCalendar  dataOd ,)javax.xml.datatype.XMLGregorianCalendar  dataDo ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  idPrzesylek )*
     */
    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend pobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres(java.lang.String userName,java.lang.String password,java.lang.String apiKey,javax.xml.datatype.XMLGregorianCalendar dataOd,javax.xml.datatype.XMLGregorianCalendar dataDo,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid idPrzesylek) throws IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage , IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(dataOd);
        System.out.println(dataDo);
        System.out.println(idPrzesylek);
        try {
            org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres_HistoriaPrzesylkiOutputDataExtendFault_FaultMessage...");
        //throw new IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzNumeryNadawczePrzesylekZaOkres(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)javax.xml.datatype.XMLGregorianCalendar  dataOd ,)javax.xml.datatype.XMLGregorianCalendar  dataDo )*
     */
    public org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData pobierzNumeryNadawczePrzesylekZaOkres(java.lang.String userName,java.lang.String password,java.lang.String apiKey,javax.xml.datatype.XMLGregorianCalendar dataOd,javax.xml.datatype.XMLGregorianCalendar dataDo) throws IEpoContractPobierzNumeryNadawczePrzesylekZaOkresOutputDataFaultFaultMessage , IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzNumeryNadawczePrzesylekZaOkres");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(dataOd);
        System.out.println(dataDo);
        try {
            org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzNumeryNadawczePrzesylekZaOkresOutputDataFaultFaultMessage("IEpoContract_PobierzNumeryNadawczePrzesylekZaOkres_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage("IEpoContract_PobierzNumeryNadawczePrzesylekZaOkres_NumerNadawczyOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#importZbioruEknBase64(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  base64Xml )*
     */
    public org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData importZbioruEknBase64(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String base64Xml) throws IEpoContractImportZbioruEknBase64OutputDataFaultFaultMessage , IEpoContractImportZbioruEknBase64ImportZbiorEknOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation importZbioruEknBase64");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(base64Xml);
        try {
            org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractImportZbioruEknBase64OutputDataFaultFaultMessage("IEpoContract_ImportZbioruEknBase64_OutputDataFault_FaultMessage...");
        //throw new IEpoContractImportZbioruEknBase64ImportZbiorEknOutputDataFaultFaultMessage("IEpoContract_ImportZbioruEknBase64_ImportZbiorEknOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzPdfPotwierdzeniaDoreczenPoGuidach(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  guidPrzesylki )*
     */
    public org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData pobierzPdfPotwierdzeniaDoreczenPoGuidach(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki) throws IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage , IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzPdfPotwierdzeniaDoreczenPoGuidach");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(guidPrzesylki);
        try {
            org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage("IEpoContract_PobierzPdfPotwierdzeniaDoreczenPoGuidach_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage("IEpoContract_PobierzPdfPotwierdzeniaDoreczenPoGuidach_ListaDoreczenPdfOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzXmlPotwierdzeniaDoreczenPoGuidach(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  guidPrzesylki )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzXmlPotwierdzeniaDoreczenPoGuidach(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki) throws IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage , IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzXmlPotwierdzeniaDoreczenPoGuidach");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(guidPrzesylki);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage("IEpoContract_PobierzXmlPotwierdzeniaDoreczenPoGuidach_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage("IEpoContract_PobierzXmlPotwierdzeniaDoreczenPoGuidach_ListaDoreczenPdfOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzKodyPocztowe(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.Integer  pageIndex ,)java.lang.Integer  pageSize ,)javax.xml.datatype.XMLGregorianCalendar  dataOd ,)javax.xml.datatype.XMLGregorianCalendar  dataDo ,)java.lang.String  maska )*
     */
    public org.datacontract.schemas._2004._07.epowslib.KodPocztowyOutputData pobierzKodyPocztowe(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.Integer pageIndex,java.lang.Integer pageSize,javax.xml.datatype.XMLGregorianCalendar dataOd,javax.xml.datatype.XMLGregorianCalendar dataDo,java.lang.String maska) throws IEpoContractPobierzKodyPocztoweOutputDataFaultFaultMessage , IEpoContractPobierzKodyPocztoweKodPocztowyOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzKodyPocztowe");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(pageIndex);
        System.out.println(pageSize);
        System.out.println(dataOd);
        System.out.println(dataDo);
        System.out.println(maska);
        try {
            org.datacontract.schemas._2004._07.epowslib.KodPocztowyOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzKodyPocztoweOutputDataFaultFaultMessage("IEpoContract_PobierzKodyPocztowe_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzKodyPocztoweKodPocztowyOutputDataFaultFaultMessage("IEpoContract_PobierzKodyPocztowe_KodPocztowyOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekPoNumerachNadawczychShort(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring  numeryNadawcze ,)java.lang.Integer  distinct )*
     */
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData pobierzStatusyPrzesylekPoNumerachNadawczychShort(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze,java.lang.Integer distinct) throws IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortPrzesylkiOutputShortDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekPoNumerachNadawczychShort");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numeryNadawcze);
        System.out.println(distinct);
        try {
            org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortPrzesylkiOutputShortDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoNumerachNadawczychShort_PrzesylkiOutputShortDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoNumerachNadawczychShort_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekPoGuidachShort(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid  guidPrzesylki ,)java.lang.Integer  distinct )*
     */
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData pobierzStatusyPrzesylekPoGuidachShort(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki,java.lang.Integer distinct) throws IEpoContractPobierzStatusyPrzesylekPoGuidachShortPrzesylkiOutputShortDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekPoGuidachShortOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekPoGuidachShort");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(guidPrzesylki);
        System.out.println(distinct);
        try {
            org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekPoGuidachShortPrzesylkiOutputShortDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoGuidachShort_PrzesylkiOutputShortDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekPoGuidachShortOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekPoGuidachShort_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzStatusyPrzesylekXml(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.Integer  pageIndex ,)java.lang.Integer  pageSize ,)java.lang.String  sortColumn ,)java.lang.String  sortDirection ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringstring  filtersValues )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzStatusyPrzesylekXml(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.Integer pageIndex,java.lang.Integer pageSize,java.lang.String sortColumn,java.lang.String sortDirection,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringstring filtersValues) throws IEpoContractPobierzStatusyPrzesylekXmlPrzesylkiOutputDataFaultFaultMessage , IEpoContractPobierzStatusyPrzesylekXmlOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzStatusyPrzesylekXml");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(pageIndex);
        System.out.println(pageSize);
        System.out.println(sortColumn);
        System.out.println(sortDirection);
        System.out.println(filtersValues);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzStatusyPrzesylekXmlPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekXml_PrzesylkiOutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzStatusyPrzesylekXmlOutputDataFaultFaultMessage("IEpoContract_PobierzStatusyPrzesylekXml_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#nadanieZbioruEkn(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  xml )*
     */
    public org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData nadanieZbioruEkn(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String xml) throws IEpoContractNadanieZbioruEknOutputDataFaultFaultMessage , IEpoContractNadanieZbioruEknNadajZbiorEknOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation nadanieZbioruEkn");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(xml);
        try {
            org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractNadanieZbioruEknOutputDataFaultFaultMessage("IEpoContract_NadanieZbioruEkn_OutputDataFault_FaultMessage...");
        //throw new IEpoContractNadanieZbioruEknNadajZbiorEknOutputDataFaultFaultMessage("IEpoContract_NadanieZbioruEkn_NadajZbiorEknOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#nadanieZbioruEknBase64(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  base64Xml )*
     */
    public org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData nadanieZbioruEknBase64(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String base64Xml) throws IEpoContractNadanieZbioruEknBase64OutputDataFaultFaultMessage , IEpoContractNadanieZbioruEknBase64NadajZbiorEknOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation nadanieZbioruEknBase64");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(base64Xml);
        try {
            org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractNadanieZbioruEknBase64OutputDataFaultFaultMessage("IEpoContract_NadanieZbioruEknBase64_OutputDataFault_FaultMessage...");
        //throw new IEpoContractNadanieZbioruEknBase64NadajZbiorEknOutputDataFaultFaultMessage("IEpoContract_NadanieZbioruEknBase64_NadajZbiorEknOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzHistoriePrzesylkiPoNumerzeNadawczymXml(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  numerNadawczy )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzHistoriePrzesylkiPoNumerzeNadawczymXml(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String numerNadawczy) throws IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlOutputDataFaultFaultMessage , IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzHistoriePrzesylkiPoNumerzeNadawczymXml");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numerNadawczy);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoNumerzeNadawczymXml_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoNumerzeNadawczymXml_HistoriaPrzesylkiOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzHistoriePrzesylkiPoGuidPrzesylkiXml(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  idPrzesylka )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzHistoriePrzesylkiPoGuidPrzesylkiXml(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String idPrzesylka) throws IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlOutputDataFaultFaultMessage , IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlHistoriaPrzesylkiOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzHistoriePrzesylkiPoGuidPrzesylkiXml");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(idPrzesylka);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoGuidPrzesylkiXml_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlHistoriaPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoGuidPrzesylkiXml_HistoriaPrzesylkiOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzWersjeApi(*
     */
    public org.datacontract.schemas._2004._07.epowslib.ApiOutputData pobierzWersjeApi() throws IEpoContractPobierzWersjeApiOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzWersjeApi");
        try {
            org.datacontract.schemas._2004._07.epowslib.ApiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzWersjeApiOutputDataFaultFaultMessage("IEpoContract_PobierzWersjeApi_OutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzHistoriePrzesylkiPoNumerzeNadawczym(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)java.lang.String  numerNadawczy )*
     */
    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData pobierzHistoriePrzesylkiPoNumerzeNadawczym(java.lang.String userName,java.lang.String password,java.lang.String apiKey,java.lang.String numerNadawczy) throws IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymOutputDataFaultFaultMessage , IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymHistoriaPrzesylkiOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzHistoriePrzesylkiPoNumerzeNadawczym");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numerNadawczy);
        try {
            org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoNumerzeNadawczym_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymHistoriaPrzesylkiOutputDataFaultFaultMessage("IEpoContract_PobierzHistoriePrzesylkiPoNumerzeNadawczym_HistoriaPrzesylkiOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzGuidyPrzesylekZaOkres(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)javax.xml.datatype.XMLGregorianCalendar  dataOd ,)javax.xml.datatype.XMLGregorianCalendar  dataDo )*
     */
    public org.datacontract.schemas._2004._07.epowslib.GuidOutputData pobierzGuidyPrzesylekZaOkres(java.lang.String userName,java.lang.String password,java.lang.String apiKey,javax.xml.datatype.XMLGregorianCalendar dataOd,javax.xml.datatype.XMLGregorianCalendar dataDo) throws IEpoContractPobierzGuidyPrzesylekZaOkresOutputDataFaultFaultMessage , IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzGuidyPrzesylekZaOkres");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(dataOd);
        System.out.println(dataDo);
        try {
            org.datacontract.schemas._2004._07.epowslib.GuidOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzGuidyPrzesylekZaOkresOutputDataFaultFaultMessage("IEpoContract_PobierzGuidyPrzesylekZaOkres_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage("IEpoContract_PobierzGuidyPrzesylekZaOkres_GuidOutputDataFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see pl.gov.ms.msepo.IEpoContract#pobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  apiKey ,)com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring  numeryNadawcze )*
     */
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych(java.lang.String userName,java.lang.String password,java.lang.String apiKey,com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze) throws IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage , IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage    { 
        LOG.info("Executing operation pobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(apiKey);
        System.out.println(numeryNadawcze);
        try {
            org.datacontract.schemas._2004._07.epowslib.XmlOutputData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage("IEpoContract_PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych_OutputDataFault_FaultMessage...");
        //throw new IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage("IEpoContract_PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych_ListaDoreczenPdfOutputDataFault_FaultMessage...");
    }

}
