
package pl.gov.ms.msepo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:36.875+01:00
 * Generated source version: 3.0.6
 */

@WebFault(name = "HistoriaPrzesylkiOutputDataExtend", targetNamespace = "http://schemas.datacontract.org/2004/07/EpoWSLib.DataTypes")
public class IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend historiaPrzesylkiOutputDataExtend;

    public IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage() {
        super();
    }
    
    public IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend historiaPrzesylkiOutputDataExtend) {
        super(message);
        this.historiaPrzesylkiOutputDataExtend = historiaPrzesylkiOutputDataExtend;
    }

    public IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend historiaPrzesylkiOutputDataExtend, Throwable cause) {
        super(message, cause);
        this.historiaPrzesylkiOutputDataExtend = historiaPrzesylkiOutputDataExtend;
    }

    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend getFaultInfo() {
        return this.historiaPrzesylkiOutputDataExtend;
    }
}
