
package pl.gov.ms.msepo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:36.875+01:00
 * Generated source version: 3.0.6
 */

@WebFault(name = "PrzesylkiOutputData", targetNamespace = "http://schemas.datacontract.org/2004/07/EpoWSLib.DataTypes")
public class IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData przesylkiOutputData;

    public IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage() {
        super();
    }
    
    public IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData przesylkiOutputData) {
        super(message);
        this.przesylkiOutputData = przesylkiOutputData;
    }

    public IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData przesylkiOutputData, Throwable cause) {
        super(message, cause);
        this.przesylkiOutputData = przesylkiOutputData;
    }

    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData getFaultInfo() {
        return this.przesylkiOutputData;
    }
}
