
package pl.gov.ms.msepo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:36.797+01:00
 * Generated source version: 3.0.6
 */

@WebFault(name = "ListaDoreczenPdfOutputData", targetNamespace = "http://schemas.datacontract.org/2004/07/EpoWSLib.DataTypes")
public class IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData listaDoreczenPdfOutputData;

    public IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage() {
        super();
    }
    
    public IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData listaDoreczenPdfOutputData) {
        super(message);
        this.listaDoreczenPdfOutputData = listaDoreczenPdfOutputData;
    }

    public IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData listaDoreczenPdfOutputData, Throwable cause) {
        super(message, cause);
        this.listaDoreczenPdfOutputData = listaDoreczenPdfOutputData;
    }

    public org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData getFaultInfo() {
        return this.listaDoreczenPdfOutputData;
    }
}
