
package pl.gov.ms.msepo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:37.079+01:00
 * Generated source version: 3.0.6
 */

@WebFault(name = "GuidOutputData", targetNamespace = "http://schemas.datacontract.org/2004/07/EpoWSLib.DataTypes")
public class IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.epowslib.GuidOutputData guidOutputData;

    public IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage() {
        super();
    }
    
    public IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.GuidOutputData guidOutputData) {
        super(message);
        this.guidOutputData = guidOutputData;
    }

    public IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.GuidOutputData guidOutputData, Throwable cause) {
        super(message, cause);
        this.guidOutputData = guidOutputData;
    }

    public org.datacontract.schemas._2004._07.epowslib.GuidOutputData getFaultInfo() {
        return this.guidOutputData;
    }
}
