
package pl.gov.ms.msepo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:37.047+01:00
 * Generated source version: 3.0.6
 */

@WebFault(name = "HistoriaPrzesylkiOutputData", targetNamespace = "http://schemas.datacontract.org/2004/07/EpoWSLib.DataTypes")
public class IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData historiaPrzesylkiOutputData;

    public IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage() {
        super();
    }
    
    public IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData historiaPrzesylkiOutputData) {
        super(message);
        this.historiaPrzesylkiOutputData = historiaPrzesylkiOutputData;
    }

    public IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData historiaPrzesylkiOutputData, Throwable cause) {
        super(message, cause);
        this.historiaPrzesylkiOutputData = historiaPrzesylkiOutputData;
    }

    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData getFaultInfo() {
        return this.historiaPrzesylkiOutputData;
    }
}
