package pl.gov.ms.msepo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:37.157+01:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://ms.gov.pl/msepo", name = "IEpoContract")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.domain.ObjectFactory.class, org.datacontract.schemas._2004._07.epowslib.ObjectFactory.class, ObjectFactory.class})
public interface IEpoContract {

    @WebMethod(operationName = "PobierzStatusyPrzesylekPoGuidach", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidach")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidach", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoGuidachPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoGuidachOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekPoGuidach", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoGuidach")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekPoGuidachResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoGuidachResponse")
    @WebResult(name = "PobierzStatusyPrzesylekPoGuidachResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData pobierzStatusyPrzesylekPoGuidach(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "guidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki
    ) throws IEpoContractPobierzStatusyPrzesylekPoGuidachPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekPoGuidachOutputDataFaultFaultMessage;

    @WebMethod(operationName = "ImportZbioruEkn", action = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEkn")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEkn", output = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknResponse", fault = {@FaultAction(className = IEpoContractImportZbioruEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknOutputDataFault"), @FaultAction(className = IEpoContractImportZbioruEknImportZbiorEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknImportZbiorEknOutputDataFault")})
    @RequestWrapper(localName = "ImportZbioruEkn", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.ImportZbioruEkn")
    @ResponseWrapper(localName = "ImportZbioruEknResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.ImportZbioruEknResponse")
    @WebResult(name = "ImportZbioruEknResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData importZbioruEkn(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "xml", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String xml
    ) throws IEpoContractImportZbioruEknOutputDataFaultFaultMessage, IEpoContractImportZbioruEknImportZbiorEknOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekPoNumerachNadawczych", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczych")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczych", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekPoNumerachNadawczych", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoNumerachNadawczych")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekPoNumerachNadawczychResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoNumerachNadawczychResponse")
    @WebResult(name = "PobierzStatusyPrzesylekPoNumerachNadawczychResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData pobierzStatusyPrzesylekPoNumerachNadawczych(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numeryNadawcze", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze
    ) throws IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekZaOkres", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekZaOkres")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekZaOkres", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekZaOkresResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekZaOkresPrzesylkiOutputShortDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekZaOkresPrzesylkiOutputShortDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekZaOkresOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekZaOkresOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekZaOkres", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekZaOkres")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekZaOkresResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekZaOkresResponse")
    @WebResult(name = "PobierzStatusyPrzesylekZaOkresResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData pobierzStatusyPrzesylekZaOkres(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "dataOd", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataOd,
        @WebParam(name = "dataDo", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataDo,
        @WebParam(name = "guidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki,
        @WebParam(name = "distinct", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer distinct
    ) throws IEpoContractPobierzStatusyPrzesylekZaOkresPrzesylkiOutputShortDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekZaOkresOutputDataFaultFaultMessage;

    @WebMethod(operationName = "ImportZbioruEknZip", action = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknZip")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknZip", output = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknZipResponse", fault = {@FaultAction(className = IEpoContractImportZbioruEknZipOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknZipOutputDataFault"), @FaultAction(className = IEpoContractImportZbioruEknZipImportZbiorEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknZipImportZbiorEknOutputDataFault")})
    @RequestWrapper(localName = "ImportZbioruEknZip", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.ImportZbioruEknZip")
    @ResponseWrapper(localName = "ImportZbioruEknZipResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.ImportZbioruEknZipResponse")
    @WebResult(name = "ImportZbioruEknZipResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData importZbioruEknZip(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "zipFile", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String zipFile
    ) throws IEpoContractImportZbioruEknZipOutputDataFaultFaultMessage, IEpoContractImportZbioruEknZipImportZbiorEknOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychResponse", fault = {@FaultAction(className = IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFault"), @FaultAction(className = IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFault")})
    @RequestWrapper(localName = "PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych")
    @ResponseWrapper(localName = "PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychResponse")
    @WebResult(name = "PobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData pobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczych(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numeryNadawcze", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze
    ) throws IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage, IEpoContractPobierzPdfPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzHistoriePrzesylkiPoGuidPrzesylki", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylki")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylki", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiResponse", fault = {@FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiHistoriaPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiHistoriaPrzesylkiOutputDataFault")})
    @RequestWrapper(localName = "PobierzHistoriePrzesylkiPoGuidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoGuidPrzesylki")
    @ResponseWrapper(localName = "PobierzHistoriePrzesylkiPoGuidPrzesylkiResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoGuidPrzesylkiResponse")
    @WebResult(name = "PobierzHistoriePrzesylkiPoGuidPrzesylkiResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData pobierzHistoriePrzesylkiPoGuidPrzesylki(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "idPrzesylka", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String idPrzesylka
    ) throws IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiHistoriaPrzesylkiOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekPoGuidachXml", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachXml")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachXml", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachXmlResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoGuidachXmlPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachXmlPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoGuidachXmlOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachXmlOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekPoGuidachXml", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoGuidachXml")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekPoGuidachXmlResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoGuidachXmlResponse")
    @WebResult(name = "PobierzStatusyPrzesylekPoGuidachXmlResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzStatusyPrzesylekPoGuidachXml(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "guidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki
    ) throws IEpoContractPobierzStatusyPrzesylekPoGuidachXmlPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekPoGuidachXmlOutputDataFaultFaultMessage;

    @WebMethod(operationName = "NadanieZbioruEknZip", action = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknZip")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknZip", output = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknZipResponse", fault = {@FaultAction(className = IEpoContractNadanieZbioruEknZipOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknZipOutputDataFault"), @FaultAction(className = IEpoContractNadanieZbioruEknZipNadajZbiorEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknZipNadajZbiorEknOutputDataFault")})
    @RequestWrapper(localName = "NadanieZbioruEknZip", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.NadanieZbioruEknZip")
    @ResponseWrapper(localName = "NadanieZbioruEknZipResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.NadanieZbioruEknZipResponse")
    @WebResult(name = "NadanieZbioruEknZipResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData nadanieZbioruEknZip(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "zipFile", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String zipFile
    ) throws IEpoContractNadanieZbioruEknZipOutputDataFaultFaultMessage, IEpoContractNadanieZbioruEknZipNadajZbiorEknOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzListeStatusowPrzesylek", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzListeStatusowPrzesylek")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzListeStatusowPrzesylek", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzListeStatusowPrzesylekResponse", fault = {@FaultAction(className = IEpoContractPobierzListeStatusowPrzesylekOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzListeStatusowPrzesylekOutputDataFault"), @FaultAction(className = IEpoContractPobierzListeStatusowPrzesylekStatusPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzListeStatusowPrzesylekStatusPrzesylkiOutputDataFault")})
    @RequestWrapper(localName = "PobierzListeStatusowPrzesylek", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzListeStatusowPrzesylek")
    @ResponseWrapper(localName = "PobierzListeStatusowPrzesylekResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzListeStatusowPrzesylekResponse")
    @WebResult(name = "PobierzListeStatusowPrzesylekResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.StatusPrzesylkiOutputData pobierzListeStatusowPrzesylek(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey
    ) throws IEpoContractPobierzListeStatusowPrzesylekOutputDataFaultFaultMessage, IEpoContractPobierzListeStatusowPrzesylekStatusPrzesylkiOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekPoNumerachNadawczychXml", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychXml")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychXml", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychXmlResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychXmlPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychXmlOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekPoNumerachNadawczychXml", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoNumerachNadawczychXml")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekPoNumerachNadawczychXmlResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoNumerachNadawczychXmlResponse")
    @WebResult(name = "PobierzStatusyPrzesylekPoNumerachNadawczychXmlResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzStatusyPrzesylekPoNumerachNadawczychXml(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numeryNadawcze", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze
    ) throws IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychXmlOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylek", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylek")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylek", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylek", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylek")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekResponse")
    @WebResult(name = "PobierzStatusyPrzesylekResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputData pobierzStatusyPrzesylek(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "pageIndex", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer pageSize,
        @WebParam(name = "sortColumn", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String sortColumn,
        @WebParam(name = "sortDirection", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String sortDirection,
        @WebParam(name = "filtersValues", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringstring filtersValues
    ) throws IEpoContractPobierzStatusyPrzesylekPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresResponse", fault = {@FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFault"), @FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresOutputDataFault")})
    @RequestWrapper(localName = "PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres")
    @ResponseWrapper(localName = "PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresResponse")
    @WebResult(name = "PobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputDataExtend pobierzHistoriePrzesylkiPoGuidPrzesylekZaOkres(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "dataOd", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataOd,
        @WebParam(name = "dataDo", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataDo,
        @WebParam(name = "idPrzesylek", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid idPrzesylek
    ) throws IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresHistoriaPrzesylkiOutputDataExtendFaultFaultMessage, IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylekZaOkresOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzNumeryNadawczePrzesylekZaOkres", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzNumeryNadawczePrzesylekZaOkres")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzNumeryNadawczePrzesylekZaOkres", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzNumeryNadawczePrzesylekZaOkresResponse", fault = {@FaultAction(className = IEpoContractPobierzNumeryNadawczePrzesylekZaOkresOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzNumeryNadawczePrzesylekZaOkresOutputDataFault"), @FaultAction(className = IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFault")})
    @RequestWrapper(localName = "PobierzNumeryNadawczePrzesylekZaOkres", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzNumeryNadawczePrzesylekZaOkres")
    @ResponseWrapper(localName = "PobierzNumeryNadawczePrzesylekZaOkresResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzNumeryNadawczePrzesylekZaOkresResponse")
    @WebResult(name = "PobierzNumeryNadawczePrzesylekZaOkresResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData pobierzNumeryNadawczePrzesylekZaOkres(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "dataOd", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataOd,
        @WebParam(name = "dataDo", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataDo
    ) throws IEpoContractPobierzNumeryNadawczePrzesylekZaOkresOutputDataFaultFaultMessage, IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage;

    @WebMethod(operationName = "ImportZbioruEknBase64", action = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknBase64")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknBase64", output = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknBase64Response", fault = {@FaultAction(className = IEpoContractImportZbioruEknBase64OutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknBase64OutputDataFault"), @FaultAction(className = IEpoContractImportZbioruEknBase64ImportZbiorEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/ImportZbioruEknBase64ImportZbiorEknOutputDataFault")})
    @RequestWrapper(localName = "ImportZbioruEknBase64", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.ImportZbioruEknBase64")
    @ResponseWrapper(localName = "ImportZbioruEknBase64Response", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.ImportZbioruEknBase64Response")
    @WebResult(name = "ImportZbioruEknBase64Result", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.ImportZbiorEknOutputData importZbioruEknBase64(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "base64xml", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String base64Xml
    ) throws IEpoContractImportZbioruEknBase64OutputDataFaultFaultMessage, IEpoContractImportZbioruEknBase64ImportZbiorEknOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzPdfPotwierdzeniaDoreczenPoGuidach", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoGuidach")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoGuidach", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoGuidachResponse", fault = {@FaultAction(className = IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoGuidachOutputDataFault"), @FaultAction(className = IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzPdfPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFault")})
    @RequestWrapper(localName = "PobierzPdfPotwierdzeniaDoreczenPoGuidach", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzPdfPotwierdzeniaDoreczenPoGuidach")
    @ResponseWrapper(localName = "PobierzPdfPotwierdzeniaDoreczenPoGuidachResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzPdfPotwierdzeniaDoreczenPoGuidachResponse")
    @WebResult(name = "PobierzPdfPotwierdzeniaDoreczenPoGuidachResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.ListaDoreczenPdfOutputData pobierzPdfPotwierdzeniaDoreczenPoGuidach(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "guidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki
    ) throws IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage, IEpoContractPobierzPdfPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzXmlPotwierdzeniaDoreczenPoGuidach", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoGuidach")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoGuidach", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoGuidachResponse", fault = {@FaultAction(className = IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoGuidachOutputDataFault"), @FaultAction(className = IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFault")})
    @RequestWrapper(localName = "PobierzXmlPotwierdzeniaDoreczenPoGuidach", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzXmlPotwierdzeniaDoreczenPoGuidach")
    @ResponseWrapper(localName = "PobierzXmlPotwierdzeniaDoreczenPoGuidachResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzXmlPotwierdzeniaDoreczenPoGuidachResponse")
    @WebResult(name = "PobierzXmlPotwierdzeniaDoreczenPoGuidachResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzXmlPotwierdzeniaDoreczenPoGuidach(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "guidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki
    ) throws IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachOutputDataFaultFaultMessage, IEpoContractPobierzXmlPotwierdzeniaDoreczenPoGuidachListaDoreczenPdfOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzKodyPocztowe", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzKodyPocztowe")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzKodyPocztowe", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzKodyPocztoweResponse", fault = {@FaultAction(className = IEpoContractPobierzKodyPocztoweOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzKodyPocztoweOutputDataFault"), @FaultAction(className = IEpoContractPobierzKodyPocztoweKodPocztowyOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzKodyPocztoweKodPocztowyOutputDataFault")})
    @RequestWrapper(localName = "PobierzKodyPocztowe", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzKodyPocztowe")
    @ResponseWrapper(localName = "PobierzKodyPocztoweResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzKodyPocztoweResponse")
    @WebResult(name = "PobierzKodyPocztoweResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.KodPocztowyOutputData pobierzKodyPocztowe(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "pageIndex", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer pageSize,
        @WebParam(name = "dataOd", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataOd,
        @WebParam(name = "dataDo", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataDo,
        @WebParam(name = "maska", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String maska
    ) throws IEpoContractPobierzKodyPocztoweOutputDataFaultFaultMessage, IEpoContractPobierzKodyPocztoweKodPocztowyOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekPoNumerachNadawczychShort", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychShort")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychShort", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychShortResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortPrzesylkiOutputShortDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychShortPrzesylkiOutputShortDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoNumerachNadawczychShortOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekPoNumerachNadawczychShort", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoNumerachNadawczychShort")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekPoNumerachNadawczychShortResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoNumerachNadawczychShortResponse")
    @WebResult(name = "PobierzStatusyPrzesylekPoNumerachNadawczychShortResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData pobierzStatusyPrzesylekPoNumerachNadawczychShort(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numeryNadawcze", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze,
        @WebParam(name = "distinct", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer distinct
    ) throws IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortPrzesylkiOutputShortDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekPoNumerachNadawczychShortOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekPoGuidachShort", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachShort")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachShort", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachShortResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoGuidachShortPrzesylkiOutputShortDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachShortPrzesylkiOutputShortDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekPoGuidachShortOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekPoGuidachShortOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekPoGuidachShort", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoGuidachShort")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekPoGuidachShortResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekPoGuidachShortResponse")
    @WebResult(name = "PobierzStatusyPrzesylekPoGuidachShortResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.PrzesylkiOutputShortData pobierzStatusyPrzesylekPoGuidachShort(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "guidPrzesylki", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid guidPrzesylki,
        @WebParam(name = "distinct", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer distinct
    ) throws IEpoContractPobierzStatusyPrzesylekPoGuidachShortPrzesylkiOutputShortDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekPoGuidachShortOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzStatusyPrzesylekXml", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekXml")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekXml", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekXmlResponse", fault = {@FaultAction(className = IEpoContractPobierzStatusyPrzesylekXmlPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekXmlPrzesylkiOutputDataFault"), @FaultAction(className = IEpoContractPobierzStatusyPrzesylekXmlOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzStatusyPrzesylekXmlOutputDataFault")})
    @RequestWrapper(localName = "PobierzStatusyPrzesylekXml", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekXml")
    @ResponseWrapper(localName = "PobierzStatusyPrzesylekXmlResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzStatusyPrzesylekXmlResponse")
    @WebResult(name = "PobierzStatusyPrzesylekXmlResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzStatusyPrzesylekXml(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "pageIndex", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.Integer pageSize,
        @WebParam(name = "sortColumn", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String sortColumn,
        @WebParam(name = "sortDirection", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String sortDirection,
        @WebParam(name = "filtersValues", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringstring filtersValues
    ) throws IEpoContractPobierzStatusyPrzesylekXmlPrzesylkiOutputDataFaultFaultMessage, IEpoContractPobierzStatusyPrzesylekXmlOutputDataFaultFaultMessage;

    @WebMethod(operationName = "NadanieZbioruEkn", action = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEkn")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEkn", output = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknResponse", fault = {@FaultAction(className = IEpoContractNadanieZbioruEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknOutputDataFault"), @FaultAction(className = IEpoContractNadanieZbioruEknNadajZbiorEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknNadajZbiorEknOutputDataFault")})
    @RequestWrapper(localName = "NadanieZbioruEkn", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.NadanieZbioruEkn")
    @ResponseWrapper(localName = "NadanieZbioruEknResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.NadanieZbioruEknResponse")
    @WebResult(name = "NadanieZbioruEknResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData nadanieZbioruEkn(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "xml", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String xml
    ) throws IEpoContractNadanieZbioruEknOutputDataFaultFaultMessage, IEpoContractNadanieZbioruEknNadajZbiorEknOutputDataFaultFaultMessage;

    @WebMethod(operationName = "NadanieZbioruEknBase64", action = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknBase64")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknBase64", output = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknBase64Response", fault = {@FaultAction(className = IEpoContractNadanieZbioruEknBase64OutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknBase64OutputDataFault"), @FaultAction(className = IEpoContractNadanieZbioruEknBase64NadajZbiorEknOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/NadanieZbioruEknBase64NadajZbiorEknOutputDataFault")})
    @RequestWrapper(localName = "NadanieZbioruEknBase64", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.NadanieZbioruEknBase64")
    @ResponseWrapper(localName = "NadanieZbioruEknBase64Response", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.NadanieZbioruEknBase64Response")
    @WebResult(name = "NadanieZbioruEknBase64Result", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.NadajZbiorEknOutputData nadanieZbioruEknBase64(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "base64xml", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String base64Xml
    ) throws IEpoContractNadanieZbioruEknBase64OutputDataFaultFaultMessage, IEpoContractNadanieZbioruEknBase64NadajZbiorEknOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzHistoriePrzesylkiPoNumerzeNadawczymXml", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymXml")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymXml", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymXmlResponse", fault = {@FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymXmlOutputDataFault"), @FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFault")})
    @RequestWrapper(localName = "PobierzHistoriePrzesylkiPoNumerzeNadawczymXml", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoNumerzeNadawczymXml")
    @ResponseWrapper(localName = "PobierzHistoriePrzesylkiPoNumerzeNadawczymXmlResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoNumerzeNadawczymXmlResponse")
    @WebResult(name = "PobierzHistoriePrzesylkiPoNumerzeNadawczymXmlResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzHistoriePrzesylkiPoNumerzeNadawczymXml(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numerNadawczy", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String numerNadawczy
    ) throws IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlOutputDataFaultFaultMessage, IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymXmlHistoriaPrzesylkiOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzHistoriePrzesylkiPoGuidPrzesylkiXml", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiXml")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiXml", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiXmlResponse", fault = {@FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiXmlOutputDataFault"), @FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlHistoriaPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoGuidPrzesylkiXmlHistoriaPrzesylkiOutputDataFault")})
    @RequestWrapper(localName = "PobierzHistoriePrzesylkiPoGuidPrzesylkiXml", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoGuidPrzesylkiXml")
    @ResponseWrapper(localName = "PobierzHistoriePrzesylkiPoGuidPrzesylkiXmlResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoGuidPrzesylkiXmlResponse")
    @WebResult(name = "PobierzHistoriePrzesylkiPoGuidPrzesylkiXmlResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzHistoriePrzesylkiPoGuidPrzesylkiXml(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "idPrzesylka", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String idPrzesylka
    ) throws IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlOutputDataFaultFaultMessage, IEpoContractPobierzHistoriePrzesylkiPoGuidPrzesylkiXmlHistoriaPrzesylkiOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzWersjeApi", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzWersjeApi")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzWersjeApi", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzWersjeApiResponse", fault = {@FaultAction(className = IEpoContractPobierzWersjeApiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzWersjeApiOutputDataFault")})
    @RequestWrapper(localName = "PobierzWersjeApi", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzWersjeApi")
    @ResponseWrapper(localName = "PobierzWersjeApiResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzWersjeApiResponse")
    @WebResult(name = "PobierzWersjeApiResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.ApiOutputData pobierzWersjeApi() throws IEpoContractPobierzWersjeApiOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzHistoriePrzesylkiPoNumerzeNadawczym", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczym")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczym", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymResponse", fault = {@FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymOutputDataFault"), @FaultAction(className = IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymHistoriaPrzesylkiOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzHistoriePrzesylkiPoNumerzeNadawczymHistoriaPrzesylkiOutputDataFault")})
    @RequestWrapper(localName = "PobierzHistoriePrzesylkiPoNumerzeNadawczym", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoNumerzeNadawczym")
    @ResponseWrapper(localName = "PobierzHistoriePrzesylkiPoNumerzeNadawczymResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzHistoriePrzesylkiPoNumerzeNadawczymResponse")
    @WebResult(name = "PobierzHistoriePrzesylkiPoNumerzeNadawczymResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.HistoriaPrzesylkiOutputData pobierzHistoriePrzesylkiPoNumerzeNadawczym(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numerNadawczy", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String numerNadawczy
    ) throws IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymOutputDataFaultFaultMessage, IEpoContractPobierzHistoriePrzesylkiPoNumerzeNadawczymHistoriaPrzesylkiOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzGuidyPrzesylekZaOkres", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzGuidyPrzesylekZaOkres")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzGuidyPrzesylekZaOkres", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzGuidyPrzesylekZaOkresResponse", fault = {@FaultAction(className = IEpoContractPobierzGuidyPrzesylekZaOkresOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzGuidyPrzesylekZaOkresOutputDataFault"), @FaultAction(className = IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzGuidyPrzesylekZaOkresGuidOutputDataFault")})
    @RequestWrapper(localName = "PobierzGuidyPrzesylekZaOkres", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzGuidyPrzesylekZaOkres")
    @ResponseWrapper(localName = "PobierzGuidyPrzesylekZaOkresResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzGuidyPrzesylekZaOkresResponse")
    @WebResult(name = "PobierzGuidyPrzesylekZaOkresResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.GuidOutputData pobierzGuidyPrzesylekZaOkres(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "dataOd", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataOd,
        @WebParam(name = "dataDo", targetNamespace = "http://ms.gov.pl/msepo")
        javax.xml.datatype.XMLGregorianCalendar dataDo
    ) throws IEpoContractPobierzGuidyPrzesylekZaOkresOutputDataFaultFaultMessage, IEpoContractPobierzGuidyPrzesylekZaOkresGuidOutputDataFaultFaultMessage;

    @WebMethod(operationName = "PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych", action = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych")
    @Action(input = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych", output = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychResponse", fault = {@FaultAction(className = IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFault"), @FaultAction(className = IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage.class, value = "http://ms.gov.pl/msepo/IEpoContract/PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFault")})
    @RequestWrapper(localName = "PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych")
    @ResponseWrapper(localName = "PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychResponse", targetNamespace = "http://ms.gov.pl/msepo", className = "pl.gov.ms.msepo.PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychResponse")
    @WebResult(name = "PobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychResult", targetNamespace = "http://ms.gov.pl/msepo")
    public org.datacontract.schemas._2004._07.epowslib.XmlOutputData pobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczych(
        @WebParam(name = "userName", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String password,
        @WebParam(name = "apiKey", targetNamespace = "http://ms.gov.pl/msepo")
        java.lang.String apiKey,
        @WebParam(name = "numeryNadawcze", targetNamespace = "http://ms.gov.pl/msepo")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring numeryNadawcze
    ) throws IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychOutputDataFaultFaultMessage, IEpoContractPobierzXmlPotwierdzeniaDoreczenPoNumerachNadawczychListaDoreczenPdfOutputDataFaultFaultMessage;
}
