
package pl.gov.ms.msepo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-11T12:55:36.907+01:00
 * Generated source version: 3.0.6
 */

@WebFault(name = "NumerNadawczyOutputData", targetNamespace = "http://schemas.datacontract.org/2004/07/EpoWSLib.DataTypes")
public class IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData numerNadawczyOutputData;

    public IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage() {
        super();
    }
    
    public IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData numerNadawczyOutputData) {
        super(message);
        this.numerNadawczyOutputData = numerNadawczyOutputData;
    }

    public IEpoContractPobierzNumeryNadawczePrzesylekZaOkresNumerNadawczyOutputDataFaultFaultMessage(String message, org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData numerNadawczyOutputData, Throwable cause) {
        super(message, cause);
        this.numerNadawczyOutputData = numerNadawczyOutputData;
    }

    public org.datacontract.schemas._2004._07.epowslib.NumerNadawczyOutputData getFaultInfo() {
        return this.numerNadawczyOutputData;
    }
}
